version: '3.8'

services:

  db:
    container_name: fitbot-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: fitbot
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
